greeting:
  message : Welcome to the Simple Project

server:
  port: 0

spring:
  application:
    name: user-service
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#    enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: cgs2760
#  profiles:
#    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: customer-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url : jdbc:h2:/~/ecommerce
#    username: admin
#    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411
logging:
  level:
    com.example.usermicroservice.client: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"