greeting:
  message : Welcome to the Simple Project

server:
  port: 0

spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    config:
      name: ecommerce
  config:
    import: "optional:configserver:http://localhost:8888/"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:tcp://localhost/~/ecommerce
    username: admin
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
#token:
#  expiration_time: 86400000
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
#  secret: "236979CB6F1AD6B6A6184A8CC36871E26235DD67DCFE404149231E6BE37DB3818CC36871E26235DD67DCFE4041492"