server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: cgs2760
  profiles:
    active: symmetricKey
  cloud:
   config:
      server:
        git:
          uri: https://github.com/ChaeJongMin/spring-cloud-config
#        native:
#          search-locations: file:///${user.home}/native-file-repos

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh